# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-06 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLShrink_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlname',
            name='id',
        ),
        migrations.AlterField(
            model_name='urlname',
            name='full_URL',
            field=models.CharField(default='Enter in the full URL', max_length=2083),
        ),
        migrations.AlterField(
            model_name='urlname',
            name='nick_name',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
