# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-06 02:36
from __future__ import unicode_literals

import apps.URLShrink_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLShrink_app', '0002_auto_20180406_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlname',
            name='nick_name',
            field=models.CharField(default=apps.URLShrink_app.models.generateNick_Name, max_length=8, primary_key=True, serialize=False),
        ),
    ]
